cluster:
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=gxct.{rule}.{wildcards}
    --output=logs/{rule}.{wildcards}.out
    --account=pi-andyd
    --time={resources.time}
    --parsable
default-resources:
  - mem_mb="2G"
  - time="4:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 30
jobs: 500
keep-going: False
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-status: status-sacct.sh
